// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <test.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __mdds__idds__fdds_name = "fdds";

}

IceAsync::mdds::AMD_idds_fdds::AMD_idds_fdds(::IceInternal::Incoming& in) :
    ::IceInternal::IncomingAsync(in)
{
}

void
IceAsync::mdds::AMD_idds_fdds::ice_response(::Ice::Int __ret, ::Ice::Int b)
{
    if(__validateResponse(true))
    {
        try
        {
            ::IceInternal::BasicStream* __os = __startWriteParams(::Ice::DefaultFormat);
            __os->write(b);
            __os->write(__ret);
            __endWriteParams(true);
        }
        catch(const ::Ice::Exception& __ex)
        {
            __exception(__ex);
            return;
        }
        __response();
    }
}
::IceProxy::Ice::Object* ::IceProxy::mdds::upCast(::IceProxy::mdds::idds* p) { return p; }

void
::IceProxy::mdds::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::mdds::idds>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::mdds::idds;
        v->__copyFrom(proxy);
    }
}

::Ice::Int
IceProxy::mdds::idds::fdds(::Ice::Int __p_a, ::Ice::Int& __p_b, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__mdds__idds__fdds_name);
    ::IceInternal::Outgoing __og(this, __mdds__idds__fdds_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_a);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::Ice::Int __ret;
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_b);
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::mdds::idds::begin_fdds(::Ice::Int __p_a, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__mdds__idds__fdds_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __mdds__idds__fdds_name, __del, __cookie);
    try
    {
        __result->prepare(__mdds__idds__fdds_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_a);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::mdds::idds::__begin_fdds(::Ice::Int __p_a, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int, ::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (::Ice::Int, ::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::mdds::iddsPrx __proxy = ::mdds::iddsPrx::uncheckedCast(__result->getProxy());
            ::Ice::Int __p_b;
            ::Ice::Int __ret;
            try
            {
                __ret = __proxy->end_fdds(__p_b, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__ret, __p_b);
            }
        }
    
    private:
        
        ::std::function<void (::Ice::Int, ::Ice::Int)> _response;
    };
    return begin_fdds(__p_a, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

::Ice::Int
IceProxy::mdds::idds::end_fdds(::Ice::Int& __p_b, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __mdds__idds__fdds_name);
    ::Ice::Int __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_b);
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::mdds::idds::ice_staticId()
{
    return ::mdds::idds::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::mdds::idds::__newInstance() const
{
    return new idds;
}

::Ice::Object* mdds::upCast(::mdds::idds* p) { return p; }

namespace
{
const ::std::string __mdds__idds_ids[2] =
{
    "::Ice::Object",
    "::mdds::idds"
};

}

bool
mdds::idds::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__mdds__idds_ids, __mdds__idds_ids + 2, _s);
}

::std::vector< ::std::string>
mdds::idds::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__mdds__idds_ids[0], &__mdds__idds_ids[2]);
}

const ::std::string&
mdds::idds::ice_id(const ::Ice::Current&) const
{
    return __mdds__idds_ids[1];
}

const ::std::string&
mdds::idds::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::mdds::idds";
    return typeId;
#else
    return __mdds__idds_ids[1];
#endif
}

::Ice::DispatchStatus
mdds::idds::___fdds(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int __p_a;
    __is->read(__p_a);
    __inS.endReadParams();
    ::mdds::AMD_idds_fddsPtr __cb = new IceAsync::mdds::AMD_idds_fdds(__inS);
    try
    {
        fdds_async(__cb, __p_a, __current);
    }
    catch(const ::std::exception& __ex)
    {
        __cb->ice_exception(__ex);
    }
    catch(...)
    {
        __cb->ice_exception();
    }
    return ::Ice::DispatchAsync;
}

namespace
{
const ::std::string __mdds__idds_all[] =
{
    "fdds",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
mdds::idds::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__mdds__idds_all, __mdds__idds_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __mdds__idds_all)
    {
        case 0:
        {
            return ___fdds(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
mdds::idds::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
mdds::idds::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
mdds::__patch(iddsPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::mdds::iddsPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::mdds::idds::ice_staticId(), v);
    }
}
