// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __test_h__
#define __test_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <Ice/IncomingAsync.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 4
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace mdds
{

class idds;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::mdds::idds>&);
::IceProxy::Ice::Object* upCast(::IceProxy::mdds::idds*);

}

}

namespace mdds
{

class idds;
::Ice::Object* upCast(::mdds::idds*);
typedef ::IceInternal::Handle< ::mdds::idds> iddsPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::mdds::idds> iddsPrx;
void __patch(iddsPtr&, const ::Ice::ObjectPtr&);

}

namespace mdds
{

class AMD_idds_fdds : virtual public ::Ice::AMDCallback
{
public:

    virtual void ice_response(::Ice::Int, ::Ice::Int) = 0;
};

typedef ::IceUtil::Handle< ::mdds::AMD_idds_fdds> AMD_idds_fddsPtr;

}

namespace IceAsync
{

namespace mdds
{

class AMD_idds_fdds : public ::mdds::AMD_idds_fdds, public ::IceInternal::IncomingAsync
{
public:

    AMD_idds_fdds(::IceInternal::Incoming&);

    virtual void ice_response(::Ice::Int, ::Ice::Int);
};

}

}

namespace mdds
{

class Callback_idds_fdds_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_idds_fdds_Base> Callback_idds_fddsPtr;

}

namespace IceProxy
{

namespace mdds
{

class idds : virtual public ::IceProxy::Ice::Object
{
public:

    ::Ice::Int fdds(::Ice::Int __p_a, ::Ice::Int& __p_b)
    {
        return fdds(__p_a, __p_b, 0);
    }
    ::Ice::Int fdds(::Ice::Int __p_a, ::Ice::Int& __p_b, const ::Ice::Context& __ctx)
    {
        return fdds(__p_a, __p_b, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_fdds(::Ice::Int __p_a, const ::IceInternal::Function<void (::Ice::Int, ::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_fdds(__p_a, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_fdds(::Ice::Int __p_a, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_fdds(__p_a, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_fdds(::Ice::Int __p_a, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int, ::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_fdds(__p_a, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_fdds(::Ice::Int __p_a, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_fdds(__p_a, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_fdds(::Ice::Int __p_a, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int, ::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_fdds(::Ice::Int __p_a)
    {
        return begin_fdds(__p_a, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_fdds(::Ice::Int __p_a, const ::Ice::Context& __ctx)
    {
        return begin_fdds(__p_a, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_fdds(::Ice::Int __p_a, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_fdds(__p_a, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_fdds(::Ice::Int __p_a, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_fdds(__p_a, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_fdds(::Ice::Int __p_a, const ::mdds::Callback_idds_fddsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_fdds(__p_a, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_fdds(::Ice::Int __p_a, const ::Ice::Context& __ctx, const ::mdds::Callback_idds_fddsPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_fdds(__p_a, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_fdds(::Ice::Int& __p_b, const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int fdds(::Ice::Int, ::Ice::Int&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_fdds(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<idds> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_secure(bool __secure) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_twoway() const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_oneway() const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_batchOneway() const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_datagram() const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_batchDatagram() const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_compress(bool __compress) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_timeout(int __timeout) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<idds> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<idds*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace mdds
{

class idds : virtual public ::Ice::Object
{
public:

    typedef iddsPrx ProxyType;
    typedef iddsPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void fdds_async(const ::mdds::AMD_idds_fddsPtr&, ::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___fdds(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const idds& l, const idds& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const idds& l, const idds& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace mdds
{

template<class T>
class CallbackNC_idds_fdds : public Callback_idds_fdds_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int, ::Ice::Int);

    CallbackNC_idds_fdds(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::mdds::iddsPrx __proxy = ::mdds::iddsPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int b;
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_fdds(b, __result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(__ret, b);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_idds_fddsPtr
newCallback_idds_fdds(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, ::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_idds_fdds<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_idds_fddsPtr
newCallback_idds_fdds(T* instance, void (T::*cb)(::Ice::Int, ::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_idds_fdds<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_idds_fdds : public Callback_idds_fdds_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, ::Ice::Int, const CT&);

    Callback_idds_fdds(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::mdds::iddsPrx __proxy = ::mdds::iddsPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int b;
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_fdds(b, __result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(__ret, b, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_idds_fddsPtr
newCallback_idds_fdds(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, ::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_idds_fdds<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_idds_fddsPtr
newCallback_idds_fdds(T* instance, void (T::*cb)(::Ice::Int, ::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_idds_fdds<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
